-- Soporte para el nuevo recibo imprimible de Venta (calcado del formato
-- legal tradicional, igual que se hizo con el de Seña): número correlativo
-- para el encabezado y las dos firmas digitales.
alter table public.ventas add column if not exists numero bigint generated by default as identity;
alter table public.ventas add column if not exists firma_url text;
alter table public.ventas add column if not exists firma_vendedor_url text;
