-- Bug reportado por el usuario: un cliente mandó dos mensajes de WhatsApp
-- casi juntos (su primer contacto) y el bot respondió el menú de bienvenida
-- DOS VECES, una por cada mensaje. Causa: en el webhook
-- (app/api/panel/webhooks/whatsapp/[token]/route.ts), cuando Meta entrega
-- los dos mensajes en invocaciones de función separadas (casi
-- simultáneas), ambas pueden consultar "¿ya existe conversación para este
-- contacto?" ANTES de que la otra termine de insertar la primera -- las dos
-- ven que no existe y las dos crean una conversación nueva, cada una con su
-- propio mensaje. El debounce (DEBOUNCE_MS) solo protege DENTRO de una
-- misma conversación, así que no detecta que son en realidad dos
-- conversaciones duplicadas del mismo contacto, y el agente responde el
-- saludo inicial dos veces en paralelo.
--
-- El código ya asume (vía .maybeSingle() sin otro filtro que contacto_id)
-- que hay una sola conversación por contacto -- este índice lo hace
-- cumplir a nivel de base, y el insert en el webhook ahora atrapa el
-- choque (23505) y vuelve a consultar, mismo patrón que ya usa
-- whatsapp_contactos para la misma clase de carrera.
CREATE UNIQUE INDEX IF NOT EXISTS whatsapp_conversaciones_contacto_unico ON whatsapp_conversaciones (contacto_id);
