alter table public.senas
  add column if not exists cuenta_orden_apellido_nombre text,
  add column if not exists cuenta_orden_dni text,
  add column if not exists cuenta_orden_direccion text,
  add column if not exists efectivo_ars numeric,
  add column if not exists efectivo_usd numeric,
  add column if not exists permuta_vehiculo_id uuid references public.vehiculos(id),
  add column if not exists permuta_tasado_ars numeric,
  add column if not exists remanente_ars numeric,
  add column if not exists fecha_primera_cuota_remanente date,
  add column if not exists cant_cuotas_remanente integer,
  add column if not exists cuota_remanente_ars numeric,
  add column if not exists banco_prenda text,
  add column if not exists prenda_monto numeric,
  add column if not exists cant_cuotas_prenda integer,
  add column if not exists cuota_prenda_ars numeric,
  add column if not exists seguro_prenda_ars numeric,
  add column if not exists seguro_compania text,
  add column if not exists seguro_importe_mensual numeric,
  add column if not exists saldo_abonar_ars numeric;
