// Única fuente de verdad de logos de marca — usado tanto en components/Marcas.tsx
// (grilla "Buscá por marca") como en las tarjetas de auto (Stock.tsx / catálogo),
// para no duplicar la lista en dos lugares y que se desincronicen.
export const LOGOS_MARCAS: Record<string, string> = {
  "Volkswagen": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Volkswagen_logo_2019.svg",
  "Chevrolet": "/logos-marcas/chevrolet-icon.svg",
  "Toyota": "/logos-marcas/toyota-icon.svg",
  "Ford": "https://upload.wikimedia.org/wikipedia/commons/a/a0/Ford_Motor_Company_Logo.svg",
  "Peugeot": "https://upload.wikimedia.org/wikipedia/commons/f/f7/Peugeot_Logo.svg",
  "Renault": "https://upload.wikimedia.org/wikipedia/commons/a/a5/Renault_2021.svg",
  "Nissan": "https://upload.wikimedia.org/wikipedia/commons/2/23/Nissan_2020_logo.svg",
  "Honda": "https://upload.wikimedia.org/wikipedia/commons/3/38/Honda.svg",
  "Citroën": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Citro%C3%ABn_2021.svg",
  "Citroen": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Citro%C3%ABn_2021.svg",
  "Hyundai": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Hyundai_symbol.svg",
  "Kia": "https://upload.wikimedia.org/wikipedia/commons/4/47/KIA_logo2.svg",
  "Jeep": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Jeep.svg",
  "RAM": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Ram_Trucks_2025_wordmark.svg",
  "Suzuki": "https://upload.wikimedia.org/wikipedia/commons/3/31/Suzuki_Motor_Corporation_logo.svg",
  "Mitsubishi": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Mitsubishi_logo.svg",
  "BAIC": "/logos-marcas/baic-icon.png",
  "Chery": "https://upload.wikimedia.org/wikipedia/commons/b/b6/Chery_logo.svg",
  "BYD": "https://upload.wikimedia.org/wikipedia/commons/9/99/BYD_Company%2C_Ltd._-_Logo.svg",
  "Geely": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Geely_Auto_2023.svg",
  "Haval": "https://upload.wikimedia.org/wikipedia/commons/d/da/Haval_2023_logo.svg",
  "JAC": "https://upload.wikimedia.org/wikipedia/commons/d/de/New_Jac_motors_logo.png",
  "Audi": "https://upload.wikimedia.org/wikipedia/commons/9/92/Audi-Logo_2016.svg",
  "BMW": "https://upload.wikimedia.org/wikipedia/commons/f/f4/BMW_logo_%28gray%29.svg",
  "Fiat": "https://upload.wikimedia.org/wikipedia/commons/0/05/FIAT_logo_coloured.svg",
  "Mercedes-Benz": "https://upload.wikimedia.org/wikipedia/commons/9/90/Mercedes-Logo.svg",
  "Mercedes Benz": "https://upload.wikimedia.org/wikipedia/commons/9/90/Mercedes-Logo.svg",
  "Abarth": "https://upload.wikimedia.org/wikipedia/commons/7/72/Abarth_logo.svg",
  "AION": "https://upload.wikimedia.org/wikipedia/commons/7/7a/AION_logo.svg",
  "Alfa Romeo": "https://upload.wikimedia.org/wikipedia/commons/9/98/Alfa_Romeo_2015.svg",
  "Arcfox": "https://upload.wikimedia.org/wikipedia/commons/8/85/ARCFOX_logo.svg",
  "Aston Martin": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Aston_Martin_Logo.svg",
  "BAW": "https://upload.wikimedia.org/wikipedia/commons/2/2a/BAW_logo.svg",
  "DFSK": "https://upload.wikimedia.org/wikipedia/commons/6/6a/DFSK_logo.svg",
  "Dongfeng": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Dongfeng_Motor_logo.svg",
  "DS Automobiles": "https://upload.wikimedia.org/wikipedia/commons/8/89/DS_Automobiles_logo.svg",
  "FAW": "https://upload.wikimedia.org/wikipedia/commons/6/6e/FAW_Group_logo.svg",
  "Ferrari": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Ferrari-Logo.svg",
  "Forthing": "https://upload.wikimedia.org/wikipedia/commons/c/c1/Forthing_logo.svg",
  "Foton": "https://upload.wikimedia.org/wikipedia/commons/1/12/Foton_logo.svg",
  "GAC Motor": "https://upload.wikimedia.org/wikipedia/commons/e/e6/GAC_Motor_logo.svg",
  "Great Wall": "https://upload.wikimedia.org/wikipedia/commons/5/57/Great_Wall_Motors_logo.svg",
  "GWM": "https://upload.wikimedia.org/wikipedia/commons/5/57/Great_Wall_Motors_logo.svg",
  "Isuzu": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Isuzu_logo.svg",
  "Iveco": "https://upload.wikimedia.org/wikipedia/commons/1/17/Iveco_logo.svg",
  "Jaguar": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Jaguar_logo_2021.svg",
  "Jetour": "https://upload.wikimedia.org/wikipedia/commons/9/94/Jetour_logo.svg",
  "JMC": "https://upload.wikimedia.org/wikipedia/commons/3/3a/JMC_logo.svg",
  "JMEV": "https://upload.wikimedia.org/wikipedia/commons/2/2b/JMEV_logo.svg",
  "Kaiyi": "https://upload.wikimedia.org/wikipedia/commons/6/6c/Kaiyi_logo.svg",
  "Land Rover": "https://upload.wikimedia.org/wikipedia/commons/f/f3/Land_Rover_logo_2021.svg",
  "Leapmotor": "https://upload.wikimedia.org/wikipedia/commons/8/86/Leapmotor_logo.svg",
  "Lexus": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Lexus_division_emblem.svg",
  "Lotus": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Lotus_Cars_logo.svg",
  "Lynk & Co": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Lynk_%26_Co_logo.svg",
  "Maserati": "https://upload.wikimedia.org/wikipedia/commons/2/29/Maserati_logo.svg",
  "Maxus": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Maxus_logo.svg",
  "McLaren": "https://upload.wikimedia.org/wikipedia/commons/6/66/McLaren_Racing_logo.svg",
  "MG": "https://upload.wikimedia.org/wikipedia/commons/1/1a/MG_Motor_logo.svg",
  "MINI": "https://upload.wikimedia.org/wikipedia/commons/6/66/MINI_logo.svg",
  "ORA": "https://upload.wikimedia.org/wikipedia/commons/9/97/ORA_logo.svg",
  "Porsche": "https://upload.wikimedia.org/wikipedia/commons/6/68/Porsche_Wordmark.svg",
  "Shineray": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Shineray_logo.svg",
  "Skywell": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Skywell_logo.svg",
  "KGM / SsangYong": "https://upload.wikimedia.org/wikipedia/commons/6/6a/SsangYong_Motor_logo.svg",
  "SWM": "https://upload.wikimedia.org/wikipedia/commons/8/85/SWM_logo.svg",
  "Tank": "https://upload.wikimedia.org/wikipedia/commons/4/4b/TANK_logo.svg",
  "Volvo": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Volvo_logo.svg",
};

export function getLogoMarca(marca: string | null | undefined): string | null {
  if (!marca) return null;
  return LOGOS_MARCAS[marca.trim()] || null;
}
