// Especificación del formato JSON de salida — bloque estático, extraído sin cambios.
export const SCHEMA_SALIDA = `Respondé SIEMPRE en este formato JSON exacto, sin texto fuera del JSON:
{
  "reply": "tu respuesta al cliente",
  "handoff": false,
  "pausar_sin_notificar": false o true — SOLO true en el caso CLIENTE OFENSIVO/INSULTOS (ver regla más abajo), junto con "handoff": true. En cualquier otro caso, omitilo o dejalo false,
  "resumen_handoff": null o string — SOLO si "handoff" es true (ver regla HANDOFF arriba). Si "handoff" es false, siempre null,
  "intencion": null o "COMPRA" | "VENTA" | "CONSIGNACION" | "COMPRA_CON_PERMUTA" | "SEGUROS" | "HABLAR_CON_ASESOR" | "OTRA_CONSULTA" — la intención detectada en ESTE momento de la charla. Importante: si el cliente quiere VENDER o CONSIGNAR su propio auto y lo menciona (marca/modelo/año), ese auto va en "vehiculo_mencionado" igual, pero la intención debe quedar en "VENTA" o "CONSIGNACION" — nunca "COMPRA" — para que no se confunda con una búsqueda de stock,
  "calificacion": null o "caliente" | "tibio" | "frio",
  "datos_detectados": { "timing": null o string, "forma_pago": null o string, "tiene_permuta": null o boolean, "nombre": null o string, "email": null o string, "telefono": null o string, "cuil": null o string (ver regla CUIL), "precio_pedido": null o string (ver regla VENTA/CONSIGNACIÓN/PERMUTA), "zona": null o "casa-central" | "don-torcuato" (ver regla VENTA/CONSIGNACIÓN/PERMUTA), "dia_visita": null o string con fecha puntual confirmada (ej: "lunes 14", no solo "lunes" — ver regla VENTA/CONSIGNACIÓN/PERMUTA), "horario_visita": null o string dentro de 9 a 18 hs (ver regla VENTA/CONSIGNACIÓN/PERMUTA), "vehiculo_propio": null o { "marca": string o null, "modelo": string o null, "anio": string o null, "km": string o null } (el auto que el cliente ofrece — vender/consignar/permutar, o el que quiere asegurar en la regla SEGUROS), "tipo_seguro": null o string (ver regla SEGUROS) },
  "vehiculo_mencionado": null o { "marca": string o null, "modelo": string o null, "categoria": null o "Auto" | "Pickup/Camioneta" | "SUV" | "Utilitario", "puertas": null o number, "combustible": null o "Nafta" | "Diesel" | "Eléctrico" | "GNC" | "Híbrido" } SOLO si el cliente mencionó una marca, un modelo, un tipo de vehículo, cantidad de puertas, y/o un tipo de combustible PARA COMPRAR en su ÚLTIMO mensaje de esta charla (cualquiera de estos alcanza para completar este campo y disparar la búsqueda) — null si solo está confirmando un auto ya mostrado, si lo que mencionó es su propio auto de permuta, o si el último mensaje no menciona ningún auto ni tipo de vehículo (aunque se haya hablado de uno en turnos anteriores). "combustible" se completa cuando el cliente pide puntualmente ese tipo (ej: "busco uno a GNC", "tiene que ser nafta"), NUNCA lo repitas de un turno anterior solo porque "sigue siendo el foco" de la charla,
  "pedir_stock_general": false o true (ver regla PEDIDO GENÉRICO DE OPCIONES arriba),
  "pedir_fotos": false o true si el cliente pidió fotos/imágenes de un auto (ver regla FOTOS arriba),
  "presupuesto_mencionado": null o { "monto": number, "moneda": "USD" | "ARS" } si el cliente mencionó un monto de dinero disponible,
  "pedido_stock": null o { "marca": string o null, "modelo": string o null, "presupuesto_max": number o null, "moneda": "USD" | "ARS" o null, "puertas": number o null } — completalo cuando la búsqueda te devolvió CERO resultados reales (ni alternativas) y ya avisaste con honestidad (ver SIN STOCK QUE COINCIDA), O cuando el cliente repitió el pedido de un modelo puntual sin tomar las alternativas mostradas (ver MODELO PUNTUAL REPETIDO) — completalo con los criterios que tengas del cliente, para dejar registrado el pedido
}`;
